@startuml
title Heating Control System Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "")
System(HeatingControlSystem, "Система управления отопплением", "Управление пользователями, получение данных от датчиков и управление контроллерами температур")

System_Ext(sensor, "Датчик", "Датчик температуры")
System_Ext(controller, "Контроллер", "Контроллер температуры")

Rel(user, HeatingControlSystem, "Управление отоплением\nМониторинг температуры")
Rel(HeatingControlSystem,sensor,"Получает данные о температуре")
Rel(HeatingControlSystem,controller,"Отправляет сигнал об установлении температуры")

@enduml