version: "3.0.1"

name: kong

services:

  gateway:
    container_name: kong-gateway
    image: kong
    networks:
      - kong-net
    environment:
      KONG_PG_HOST: "database"
      KONG_PG_PASSWORD: "kongpass"
      KONG_DATABASE: "postgres"
#      KONG_CASSANDRA_CONTACT_POINTS: "database"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  database:
    container_name: kong-database
    image: postgres:9.6
    networks:
      - kong-net
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
      POSTGRES_PASSWORD: "kongpass"
    ports:
      - "5432:5432"

networks:
  kong-net: